// "use client";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import SessionProvider from "./SessionProvider";
// import Navbar from "@/components/Navbar";

// import { useRouter } from 'next/navigation'
// import ProtectedRoute from '@/app/protected/page'

// const noAuthRequired = ['/', '/signin', '/signup']

// const inter = Inter({ subsets: ["latin"] });

// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// export default function RootLayout({ children }) {

//   const router = useRouter()

//   return (
//     <html lang="en">
//       {/* <SessionProvider> */}
//       {/* <body className={inter.className}>{children}</body> */}
//       {/* </SessionProvider> */}
//       <body>
        
//         <SessionProvider>
//           <Navbar />
//           {children}

          







//           </SessionProvider>
//         {/* {children} */}
//       </body>

//     </html>
//   );
// }





"use client";
import { useRouter, usePathname } from 'next/navigation';
import Navbar from '@/components/Navbar';
import ProtectedRoute from '@/app/protected/page';
import SessionProvider from './SessionProvider';
import "./globals.css";

const noAuthRequired = ['/signin', '/signup'];



export default function RootLayout({ children }) {
  const router = useRouter();

  const currentPath = usePathname()

  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <Navbar />
          {/* {children} */}
          {noAuthRequired.includes(currentPath) ? (
            children
          ) : (
            <ProtectedRoute>
              {children}
            </ProtectedRoute>
          )}
        </SessionProvider>
      </body>
    </html>
  );
}